language: node_js
node_js:
- node
cache:
  directories:
    - node_modules
script: 
    - npm install
    - npm install -g serverless
    - npm run test:coverage
deploy:
  - provider: script
    script: sls deploy
    skip_cleanup: true
    on:
      branch: master
after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls