service:
  name: typescript-lambda-quickstart

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-northeast-2

functions:
  getItems:
    handler: handlers.getItems
    events:
      - http:
          method: get
          path: api/beers
          cors: true
  getItemsCors:
    handler: handlers.corsHandler
    events:
      - http:
          method: options
          path: api/beers
          cors: true
